[package]
name = "ts-platform"
version = "0.1.0"
edition = "2024"

[dependencies]
ts-core = { path = "../ts-core" }

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6"
objc2-app-kit = { version = "0.3", default-features = false, features = [
    "NSWorkspace",
    "NSRunningApplication",
] }

objc2-foundation = "0.3"
